#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : calc
Version  : 2.12.7.2
Release  : 1
URL      : https://github.com/lcn2/calc/releases/download/2.12.7.2/calc-2.12.7.2.tar.bz2
Source0  : https://github.com/lcn2/calc/releases/download/2.12.7.2/calc-2.12.7.2.tar.bz2
Summary  : Arbitrary precision console calculator
Group    : Development/Tools
License  : LGPL-2.1
Requires: calc-license = %{version}-%{release}
BuildRequires : less
BuildRequires : util-linux

%description
# What is calc?
Calc is an interactive calculator which provides for easy large
Otherwise, it enters interactive mode.  In this mode, it accepts
commands one at a time, processes them, and displays the answers.
In the simplest case, commands are simply expressions which are
evaluated.  For example, the following line can be input:

%package license
Summary: license components for the calc package.
Group: Default

%description license
license components for the calc package.


%prep
%setup -q -n calc-2.12.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553233100
export LDFLAGS="${LDFLAGS} -fno-lto"
make


%install
export SOURCE_DATE_EPOCH=1553233100
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/calc
cp COPYING %{buildroot}/usr/share/package-licenses/calc/COPYING
cp COPYING-LGPL %{buildroot}/usr/share/package-licenses/calc/COPYING-LGPL
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/calc/COPYING
/usr/share/package-licenses/calc/COPYING-LGPL
